# Dockerfile para el frontend
FROM node:20

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación (Vite por defecto usa 5173)
EXPOSE 5173

# Comando para iniciar la aplicación frontend en modo desarrollo
CMD ["npm", "run", "dev"]
